jobs:
  include:
    - language: python
      python: 3.6
      name: "scripts"
      before_install:
        - "cd scripts/"
      script:
        - "python -m unittest discover"
    - language: node_js
      name: "server"
      node_js:
        - 10
      before_install:
        - "cd server/"
      install:
        - "npm ci"
      script:
        - "npm run build"
        - "npm test"
    - language: node_js
      name: "web"
      node_js:
        - "stable"
      before_install:
        - "cd web/"
      install:
        - "npm ci"
      script:
        - "npm run build"
        - "npm test"
