/**
 * Inserts data generated by `faker.ts` into a couchdb instance.
 */

import generateDb from "./faker";
import { importFormattedData } from "./lib/write";

console.debug("Generating mock data...");
const data = generateDb();
importFormattedData(data);
